import type { Metadata } from "next";
import { Geist_Mono } from "next/font/google";
import { ThemeProvider } from "./Components/ThemeProvider"; 
import "./globals.css"; // Import global CSS

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistMono.variable} antialiased`}
      >
        {/* Wrap the app in ThemeProvider */}
        <ThemeProvider>
          {children} {/* Render the page content */}
        </ThemeProvider>
      </body>
    </html>
  );
}
